### PR TITLE
Add Familjen Grotesk

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello!

I'm Emma, I am working with @RosaWagner to onboard fonts into the Google Fonts library. The font is now ready to be published.
Here are the few changes according to Google's specifications :
- Removed some non-necessary parameters (scale to UPM, fileName, Localized Family Name) 
- Updated font infos, added axis mapping
- We had to deactivate the feature "kerning", because it created bugs that prevented the export of the font.

Cheers,

### CODE REVIEW

**Comment by ktkm** [comment]
Thank you @emmamarichal!
Was any particular line that made the kern feature fail?
What do I need to do now?

**Comment by emmamarichal** [comment]
It's a fonttool bug, you can have a look to this issue: https://github.com/googlefonts/fontmake/issues/858

**Comment by ktkm** [comment]
I see. Thank you for the link.
How much more is needed before the typeface can go live?

**Comment by RosaWagner** [comment]
If the modifications we made are okay for you then we are all set, Emma can ship the font to GF.
Btw, the parameters we removed were either not supported by fontmake, or not impacting the font in any ways.

**Comment by ktkm** [comment]
Sounds good! Let’s ship Familjen Grotesk. 👍

**Comment by emmamarichal** [comment]
Hello @ktkm!
I'm working on your font shipping, and for the "designers" section, I was wondering if you prefer that I list all the contributors (**Anders Wikström, Jonas Bäckman, Matilda Gysing, Kristian Möller, Örjan Nordling**) or if I just write **Familjen STHLM AB**?
Depending on your choice, you can also fill in this form, so we can add your profile
https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

Thanks!

**Comment by ktkm** [comment]
Hello Emma,

Write ‘Familjen STHLM AB’.

Thank you,
Kristian

**Pull request merged**
